### ISSUE TITLE
connect to Wikidata to pull ethnicity data across

### ISSUE THREAD

**Issue by jnicho02** [openheritage/open-plaques-diversity#5]
Wikidata IDs a 'Q' codes, e.g. Sir Christopher Wren == Q170373 https://www.wikidata.org/wiki/Q170373

Use python or ruby to enhance the data

Is ethnicity data even fully available?

This must be re-runnable because the raw data csv will be updated.

Write tests and run them whilst developing

**Comment by Leo552** [comment]
Qwikidata library working. I have found that if you make repeated requests quickly most don't come through quickly. Using pandas to read data from the csv.

**Comment by Leo552** [comment]
![citizenship_1](https://user-images.githubusercontent.com/56204370/84524291-a1becd80-acd1-11ea-8d83-33097ce25a9d.png)

Initial citizenship field pulled from wikidata

**Comment by Leo552** [comment]
![Ethnic group horizontal bar chart](https://user-images.githubusercontent.com/56204370/84567014-b51f7680-ad6d-11ea-84e7-9792f9adf2f2.png)

**Comment by Leo552** [comment]
Not many of the wikidata entries contain the ethnic group as a field - only 184 out of ~ 2000.
