### ISSUE TITLE
setup Github actions to autorun tests

### ISSUE THREAD

**Issue by jnicho02** [openheritage/open-plaques-diversity#6]
Use Github actions to provide continuous integration

**Comment by Leo552** [comment]
Initial pull request does not work since it doesn't import any of the libraries. It does work locally. It is also run automatically when items are pushed.

**Comment by Leo552** [comment]
Simple test working to check a certain set of api queries against what they should be. I had to remove some libraries from the requirements.txt file to get the test to run as it couldn't find the file when testing.
