### ISSUE TITLE
legacy of slave ownership

### ISSUE THREAD

**Issue by jnicho02** [openheritage/open-plaques-diversity#7]
if a Wikidata record is linked to 'Legacies of British Slave-ownership person ID' https://www.wikidata.org/wiki/Property:P3023 such as Edward Codrington https://www.wikidata.org/wiki/Q958853 they would be suspect.

**Comment by Leo552** [comment]
Names cross checked from the wiki page at https://en.wikipedia.org/wiki/List_of_slave_owners
James Brown
William Penn
John Marshall
Robert Milligan
Hodge
Martin Van Buren
Benjamin Franklin

**Comment by jnicho02** [comment]
I believe that the 'Legacies of British Slave-ownership person ID' on Wikidata will have a very high hit rate for identifying bad actors. Better than matching to the Wikipedia list of slave owners.

Someone at UCL has researched really thoroughly who owned what (i.e. sugar plantations, and slaves) and put it in https://www.ucl.ac.uk/lbs/ ....I believe that they've been matched to Wikidata, but you'd have to check the hit rate

**Comment by Leo552** [comment]
There are 4 hits when searching the database for the Legacies of a British Slave-ownership person ID. They all have corresponding entries in the UCL database.
https://www.wikidata.org/wiki/Q3523736
https://www.ucl.ac.uk/lbs/person/view/2014903896
https://www.wikidata.org/wiki/Q160852
https://www.ucl.ac.uk/lbs/person/view/2146630326
https://www.wikidata.org/wiki/Q7347686
https://www.ucl.ac.uk/lbs/person/view/2146645741
https://www.wikidata.org/wiki/Q228494
https://www.ucl.ac.uk/lbs/person/view/2146646289

The final one is a little has a more tenuous link.
Need to check if wikidata has all entries of the UCL database.
